---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  name: file-vault
  {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: file-vault-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: file-vault
  {{ end }}
spec:
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: file-vault-{{ .DRONE_SOURCE_BRANCH }}
      service: file-vault-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: file-vault
      service: file-vault
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: file-vault-{{ .DRONE_SOURCE_BRANCH }}
        service: file-vault-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: file-vault
        service: file-vault
        {{ end }}
    spec:
      containers:
        - name: file-vault
          # v3.0.0 added July 31 2025
          image: quay.io/ukhomeofficedigital/file-vault:3.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
            requests:
              memory: 512Mi
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: configmap
                {{ end }}
          env:
            # because the internal virus scanner has a self signed cert!
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: FILE_VAULT_URL
            {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
              value: https://fv-acrs.sas.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
              value: https://fv-acrs.stg.sas.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
              value: https://fv-acrs.uat.sas-notprod.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              value: https://fv-{{ .DRONE_SOURCE_BRANCH }}.branch.sas-notprod.homeoffice.gov.uk
            - name: DEBUG
              value: "true"
            {{ end }}
            - name: PORT
              value: "3000"
            - name: CLAMAV_REST_URL
              value: https://clamav.virus-scan.svc.cluster.local/scan
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-s3-bucket
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-s3-bucket-stg
                  {{ else }}
                  name: acrs-s3-bucket-prod
                  {{ end }}
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-s3-bucket
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-s3-bucket-stg
                  {{ else }}
                  name: acrs-s3-bucket-prod
                  {{ end }}
                  key: secret_access_key
            - name: AWS_KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-s3-bucket
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-s3-bucket-stg
                  {{ else }}
                  name: acrs-s3-bucket-prod
                  {{ end }}
                  key: kms_key_id
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-s3-bucket
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-s3-bucket-stg
                  {{ else }}
                  name: acrs-s3-bucket-prod
                  {{ end }}
                  key: name
            - name: AWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ses
                  key: smtp_password
            - name: ALLOW_GENERATE_LINK_ROUTE
              value: "yes"
          securityContext:
            runAsNonRoot: true

        - name: keycloak-proxy
          image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.2.2
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
            requests:
              memory: 512Mi
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: configmap
                {{ end }}
          env:
            - name: PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: secret
            - name: PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: id
            - name: PROXY_LISTEN
              value: 127.0.0.1:3001
            - name: PROXY_UPSTREAM_URL
              value: "http://127.0.0.1:3000"
            - name: PROXY_REDIRECTION_URL
            {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
              value: https://fv-acrs.sas.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
              value: https://fv-acrs.stg.sas.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
              value: https://fv-acrs.uat.sas-notprod.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              value: https://fv-{{ .DRONE_SOURCE_BRANCH }}.branch.sas-notprod.homeoffice.gov.uk
            {{ end }}
          command:
            - "/opt/keycloak-proxy"
            - "--resources=uri=/file|methods=GET,POST|roles=caseworkers"
            - "--resources=uri=/*"
            - "--enable-logging=true"
            - "--enable-json-logging=true"
          ports:
            - containerPort: 10080
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /etc/ssl/certs
              name: bundle
              readOnly: true

        - name: nginx-proxy
          # nginx-proxy:v0.0.6
          image: quay.io/ukhomeofficedigital/hof-docker-nginx-proxy:0.0.6
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
            requests:
              memory: 512Mi
          env:
{{ file .FILEVAULT_NGINX_SETTINGS | indent 12 }}
          ports:
            - containerPort: 10080
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
            secretName: branch-tls-external
            {{ else }}
            secretName: file-vault-cert
            {{ end }}
        - name: bundle
          configMap:
            name: bundle
