---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: data-service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: data-service
  {{ end }}
spec:
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: data-service-{{ .DRONE_SOURCE_BRANCH }}
      service: data-service-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: data-service
      service: data-service
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: data-service-{{ .DRONE_SOURCE_BRANCH }}
        service: data-service-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: data-service
        service: data-service
        {{ end }}
        build: "{{.DRONE_BUILD_NUMBER}}"
        commit: "{{.DRONE_COMMIT_SHA}}"
    spec:
      containers:
        - name: data-service
          # hof-rds-api: v3.1.0 updated on 10/06/2025
          image: quay.io/ukhomeofficedigital/hof-rds-api:3.1.0@sha256:e73edb96b62bc5dbce4e56b49ac41e7b7bf2e601fb7b0b71dbd19251c8a8e317
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: configmap
                {{ end }}
          env:
            - name: SERVICE_NAME
              value: "acrs"
            - name: LATEST_MIGRATION
              value: "20240502155941_add_verify_lookup_table"
            - name: MAX_PAYLOAD_SIZE
              value: "30mb"
            - name: REQUEST_TIMEOUT
              value: "10000"
            - name: HTTPS_PORT
              value: "3443"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-notprod-rds
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-rds-stg
                  {{ else }}
                  name: acrs-rds-prod
                  {{ end }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-notprod-rds
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-rds-stg
                  {{ else }}
                  name: acrs-rds-prod
                  {{ end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-notprod-rds
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-rds-stg
                  {{ else }}
                  name: acrs-rds-prod
                  {{ end }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) }}
                  name: acrs-notprod-rds
                  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
                  name: acrs-rds-stg
                  {{ else }}
                  name: acrs-rds-prod
                  {{ end }}
          resources:
            requests:
              memory: 4Gi
              cpu: 200m
            limits:
              memory: 8Gi
              cpu: 400m
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
            secretName: branch-tls-external
            {{ else }}
            secretName: data-service-cert-cmio
            {{ end }}
